"""
🔆 TEJA — Stage 7: Supervised Fine-Tuning (SFT)
================================================
Built from zero. Trained to shine.
Created by Sabith, Nilambur, Kerala.

STAGE 7 GOAL:
    Take the Stage 5 pretrained model (which generates coherent English)
    and teach it to FOLLOW INSTRUCTIONS and HOLD CONVERSATIONS.

    Stage 5 Teja:  completes any text it's given
    Stage 7 Teja:  responds helpfully when asked a question

    This is the difference between:
        GPT-2 (raw pretraining)  → autocomplete
        ChatGPT (fine-tuned)     → assistant

    The technique is called SUPERVISED FINE-TUNING (SFT):
        - Take pretrained weights (Stage 5 checkpoint)
        - Continue training on instruction-response pairs
        - Very low learning rate (don't destroy what was learned)
        - Only a few epochs (overfit = bad)

=======================================================================
KAGGLE SETUP:
=======================================================================

    !pip install -q tiktoken datasets tqdm

    # Then in your notebook cell:
    !rm -rf teja
    !git clone https://github.com/sabithh/Teja.git teja
    %cd teja
    !mkdir -p checkpoints
    !cp "/kaggle/input/YOUR-DATASET/teja_stage5_best.pt" checkpoints/
    !python stages/stage7_sft.py

=======================================================================
CONCEPT 1: WHY FINE-TUNING WORKS
=======================================================================

    Pretraining (Stage 5) taught Teja:
        - Grammar and syntax
        - Facts about the world
        - How sentences and paragraphs are structured
        - What "question" and "answer" mean

    But it learned these by predicting the NEXT TOKEN in random web text.
    Nobody told it to be helpful.

    Fine-tuning says: "You already know language. Now learn THIS BEHAVIOR."

    Because the knowledge is already there, fine-tuning needs:
        - Much less data    (52K examples vs 150M tokens)
        - Much less compute (hours vs days)
        - Much lower LR     (1e-5 vs 3e-4 — 30x smaller)

    The pretrained weights are the foundation.
    Fine-tuning is interior decoration.

=======================================================================
CONCEPT 2: SPECIAL TOKENS
=======================================================================

    We need the model to understand conversation STRUCTURE.
    We add special tokens to mark who is speaking:

        <|system|>     — instructions for how Teja should behave
        <|user|>       — the human's message
        <|assistant|>  — Teja's response
        <|endofturn|>  — end of a turn

    A training example looks like:

        <|system|>You are Teja, a helpful AI assistant.<|endofturn|>
        <|user|>What is the capital of France?<|endofturn|>
        <|assistant|>The capital of France is Paris.<|endofturn|>

    During training, we ONLY compute loss on the <|assistant|> tokens.
    We don't penalize the model for what the user says — we only teach
    it what the assistant should say.

    This is called RESPONSE-ONLY LOSS MASKING.

=======================================================================
CONCEPT 3: THE ALPACA DATASET
=======================================================================

    We use the Stanford Alpaca dataset — 52,002 instruction-following
    examples generated by GPT-3 and cleaned by researchers.

    Each example has:
        instruction: "What is the capital of France?"
        input:       ""  (optional extra context)
        output:      "The capital of France is Paris."

    Format with input:
        <|user|>Translate to French: Hello, how are you?<|endofturn|>
        <|assistant|>Bonjour, comment allez-vous?<|endofturn|>

    Format without input (most examples):
        <|user|>What is the capital of France?<|endofturn|>
        <|assistant|>The capital of France is Paris.<|endofturn|>

=======================================================================
CONCEPT 4: RESPONSE-ONLY LOSS MASKING
=======================================================================

    In standard language modeling, we compute loss on EVERY token.
    For fine-tuning, we only want to learn the ASSISTANT's responses.

    We use a MASK to tell the loss function which tokens to ignore:

        Token:   <|user|> What  is  ... ? <|endofturn|> <|assistant|> Paris <|endofturn|>
        Mask:       -1     -1   -1  ... -1     -1           -1         1      1

    mask = -1  → ignore this token (user tokens, system tokens)
    mask =  1  → compute loss here (assistant response tokens)

    In PyTorch, we pass targets=-100 for ignored tokens.
    F.cross_entropy ignores index -100 by default.

    Without masking: model learns to predict user messages too.
    With masking:    model only learns to produce good responses.

=======================================================================
"""

import os
import sys
import math
import time
import json
import numpy as np
import torch
import torch.nn as nn
from torch.nn import functional as F

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from teja.utils import get_device, count_parameters, print_banner

torch.manual_seed(1337)

print_banner("Supervised Fine-Tuning (SFT)", 7)

device = get_device()


# ========================================================================
# HYPERPARAMETERS
# ========================================================================

# Model architecture — must match Stage 5 checkpoint exactly
n_embd     = 384
n_head     = 6
n_layer    = 6
block_size = 256
dropout    = 0.1      # lower dropout for fine-tuning
vocab_size = 50_257   # GPT-2 BPE base (special tokens added on top)

# Fine-tuning hyperparameters
learning_rate  = 1e-4    # restored — shift fix makes learning harder, need higher LR
min_lr         = 1e-5
num_epochs     = 2       # 2 epochs (~12K steps) to reach useful val loss
eval_interval  = 200     # evaluate every 200 steps
eval_iters     = 50
grad_clip      = 1.0
warmup_steps   = 200
batch_size     = 8       # smaller batch for fine-tuning (sequences are longer)
save_every     = 200     # save checkpoint every N steps regardless of val loss

# Special token ids (appended after GPT-2's 50,257 base vocab)
SYSTEM_TOKEN    = 50_257
USER_TOKEN      = 50_258
ASSISTANT_TOKEN = 50_259
EOT_TOKEN       = 50_260   # end of turn

TOTAL_VOCAB = 50_261  # 50,257 base + 4 special tokens

# Checkpoint paths
STAGE5_CKPT  = os.path.join(os.path.dirname(__file__), '..', 'checkpoints', 'teja_stage5_best.pt')
KAGGLE_S5    = '/kaggle/working/teja/checkpoints/teja_stage5_best.pt'
DRIVE_S5     = '/content/drive/MyDrive/teja_checkpoints/teja_stage5_best.pt'

BEST_CKPT    = os.path.join(os.path.dirname(__file__), '..', 'checkpoints', 'teja_stage7_best.pt')
PERIODIC_CKPT = os.path.join(os.path.dirname(__file__), '..', 'checkpoints', 'teja_stage7_latest.pt')
KAGGLE_BEST  = '/kaggle/working/teja_stage7_best.pt'
KAGGLE_LATEST = '/kaggle/working/teja_stage7_latest.pt'


# ========================================================================
# MODEL — Same TejaGPT, extended vocabulary
# ========================================================================

class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key    = nn.Linear(n_embd, head_size, bias=False)
        self.query  = nn.Linear(n_embd, head_size, bias=False)
        self.value  = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)
        q = self.query(x)
        wei = q @ k.transpose(-2, -1) * (k.shape[-1] ** -0.5)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        return wei @ self.value(x)


class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads   = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj    = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        return self.dropout(self.proj(out))


class FeedForward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.GELU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)


class Block(nn.Module):
    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size  = n_embd // n_head
        self.ln1   = nn.LayerNorm(n_embd)
        self.ln2   = nn.LayerNorm(n_embd)
        self.sa    = MultiHeadAttention(n_head, head_size)
        self.ffwd  = FeedForward(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x


class TejaGPT(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table    = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks  = nn.Sequential(*[Block(n_embd, n_head) for _ in range(n_layer)])
        self.ln_f    = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size, bias=False)
        self.token_embedding_table.weight = self.lm_head.weight

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x       = self.blocks(tok_emb + pos_emb)
        x       = self.ln_f(x)
        logits  = self.lm_head(x)

        loss = None
        if targets is not None:
            # Shift: logits[i] predicts targets[i+1] (next-token prediction)
            shift_logits  = logits[:, :-1, :].contiguous()
            shift_targets = targets[:, 1:].contiguous()
            B, T, C       = shift_logits.shape
            loss = F.cross_entropy(
                shift_logits.view(B * T, C),
                shift_targets.view(B * T),
                ignore_index=-100
            )
        return logits, loss

    @torch.no_grad()
    def generate(self, idx, max_new_tokens, temperature=0.8, top_k=50):
        for _ in range(max_new_tokens):
            idx_cond  = idx[:, -block_size:]
            logits, _ = self(idx_cond)
            logits    = logits[:, -1, :] / temperature
            if top_k is not None:
                v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
                logits[logits < v[:, [-1]]] = float('-inf')
            probs    = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx      = torch.cat((idx, idx_next), dim=1)
            # Stop at end-of-turn token
            if idx_next.item() == EOT_TOKEN:
                break
        return idx


# ========================================================================
# LOAD STAGE 5 PRETRAINED WEIGHTS
# ========================================================================

def find_stage5_checkpoint():
    for path in [STAGE5_CKPT, KAGGLE_S5, DRIVE_S5]:
        if os.path.exists(path):
            return path
    return None

stage5_path = find_stage5_checkpoint()

print(f"\nCreating TejaGPT (vocab_size={TOTAL_VOCAB} with special tokens)...")
model = TejaGPT(vocab_size=TOTAL_VOCAB).to(device)

if stage5_path:
    print(f"Loading Stage 5 weights from: {stage5_path}")
    ckpt = torch.load(stage5_path, map_location=device)
    state = ckpt['model_state_dict']

    # Stage 5 had vocab_size=50257. We extended to 50261 (4 special tokens).
    # The new embedding rows for special tokens start randomly initialized —
    # that's fine. We copy everything that matches.
    model_state = model.state_dict()
    for k, v in state.items():
        if k in model_state and model_state[k].shape == v.shape:
            model_state[k].copy_(v)
        elif k in model_state:
            print(f"  Shape mismatch for {k}: ckpt={v.shape} model={model_state[k].shape} — skipping")
    print(f"  Stage 5 weights loaded ✓  (val loss was {ckpt.get('val_loss', '?'):.4f})")
else:
    print("  WARNING: No Stage 5 checkpoint found — fine-tuning from scratch!")
    print("  Place teja_stage5_best.pt in checkpoints/ for best results.")

total_params = count_parameters(model)


# ========================================================================
# DATA: ALPACA DATASET
# ========================================================================

def prepare_sft_data(data_dir):
    """
    Download Stanford Alpaca dataset and format as conversation tokens.

    Each example is formatted as:
        [SYSTEM_TOKEN] system_text [EOT_TOKEN]
        [USER_TOKEN] user_text [EOT_TOKEN]
        [ASSISTANT_TOKEN] response_text [EOT_TOKEN]

    We create two arrays per example:
        input_ids: the full token sequence
        labels:    same as input_ids but -100 for non-assistant tokens
    """
    cache_path = os.path.join(data_dir, 'sft_data.json')

    if os.path.exists(cache_path):
        print(f"✓ SFT data already prepared: {cache_path}")
        with open(cache_path) as f:
            return json.load(f)

    print("\nPreparing Alpaca SFT dataset...")

    try:
        import tiktoken
        from datasets import load_dataset
        from tqdm import tqdm
    except ImportError:
        print("ERROR: Run: pip install tiktoken datasets tqdm")
        sys.exit(1)

    enc = tiktoken.get_encoding('gpt2')

    SYSTEM_TEXT = "You are Teja, a helpful AI assistant built from scratch."

    print("Downloading Stanford Alpaca dataset...")
    dataset = load_dataset("tatsu-lab/alpaca", split="train")
    print(f"  Loaded {len(dataset):,} examples")

    examples = []
    skipped  = 0

    for item in tqdm(dataset, desc="Formatting"):
        instruction = item['instruction'].strip()
        inp         = item['input'].strip()
        output      = item['output'].strip()

        if not instruction or not output:
            skipped += 1
            continue

        # Build user message
        if inp:
            user_text = f"{instruction}\n\n{inp}"
        else:
            user_text = instruction

        # Tokenize each part
        sys_ids   = [SYSTEM_TOKEN] + enc.encode(SYSTEM_TEXT)  + [EOT_TOKEN]
        user_ids  = [USER_TOKEN]   + enc.encode(user_text)    + [EOT_TOKEN]
        asst_ids  = [ASSISTANT_TOKEN] + enc.encode(output)    + [EOT_TOKEN]

        input_ids = sys_ids + user_ids + asst_ids

        # Labels: -100 for system+user tokens, real ids for assistant tokens
        labels = ([-100] * len(sys_ids) +
                  [-100] * len(user_ids) +
                  asst_ids)

        # Skip if too long for our context window
        if len(input_ids) > block_size:
            skipped += 1
            continue

        examples.append({
            'input_ids': input_ids,
            'labels':    labels,
        })

    print(f"\n  Formatted: {len(examples):,} examples")
    print(f"  Skipped:   {skipped:,} (too long or empty)")

    os.makedirs(data_dir, exist_ok=True)
    with open(cache_path, 'w') as f:
        json.dump(examples, f)
    print(f"  Saved to: {cache_path}")

    return examples


data_dir = os.path.join(os.path.dirname(__file__), '..', 'data', 'sft')
examples = prepare_sft_data(data_dir)

# Split 95% train / 5% val
split = int(0.95 * len(examples))
train_examples = examples[:split]
val_examples   = examples[split:]
print(f"\nTrain: {len(train_examples):,} examples")
print(f"Val:   {len(val_examples):,} examples")


# ========================================================================
# DATA LOADING
# ========================================================================

def collate_batch(batch_examples):
    """
    Pad a batch of examples to the same length and stack into tensors.

    Padding uses -100 for labels (ignored by loss) and 0 for input_ids.
    """
    max_len    = max(len(e['input_ids']) for e in batch_examples)
    input_ids  = []
    labels     = []

    for e in batch_examples:
        pad_len = max_len - len(e['input_ids'])
        input_ids.append(e['input_ids'] + [0] * pad_len)
        labels.append(e['labels']    + [-100] * pad_len)

    return (
        torch.tensor(input_ids, dtype=torch.long),
        torch.tensor(labels,    dtype=torch.long),
    )


def get_batch(split_examples, bs=None):
    if bs is None:
        bs = batch_size
    idxs    = torch.randint(len(split_examples), (bs,))
    batch   = [split_examples[i] for i in idxs]
    x, y    = collate_batch(batch)
    return x.to(device), y.to(device)


@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for name, split_data in [('train', train_examples), ('val', val_examples)]:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            x, y = get_batch(split_data, bs=4)
            _, loss = model(x, y)
            losses[k] = loss.item()
        out[name] = losses.mean()
    model.train()
    return out


# ========================================================================
# CHECKPOINT HELPERS
# ========================================================================

def save_checkpoint(path, step, val_loss, optimizer):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    data = {
        'step':                 step,
        'model_state_dict':     model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'val_loss':             val_loss,
        'vocab_size':           TOTAL_VOCAB,
        'n_embd':               n_embd,
        'n_head':               n_head,
        'n_layer':              n_layer,
        'block_size':           block_size,
    }
    torch.save(data, path)
    # Mirror to Kaggle Output root (persists after session end)
    if os.path.exists('/kaggle/working'):
        kaggle_path = path.replace(
            os.path.join(os.path.dirname(__file__), '..', 'checkpoints'),
            '/kaggle/working'
        )
        torch.save(data, kaggle_path)


def load_resume_checkpoint(optimizer):
    """Check for existing Stage 7 checkpoint and resume if found."""
    for path in [BEST_CKPT, KAGGLE_BEST]:
        if os.path.exists(path):
            print(f"Resuming Stage 7 from: {path}")
            ckpt = torch.load(path, map_location=device)
            model.load_state_dict(ckpt['model_state_dict'])
            optimizer.load_state_dict(ckpt['optimizer_state_dict'])
            return ckpt['step'], ckpt['val_loss']
    return 0, float('inf')


# ========================================================================
# LR SCHEDULER
# ========================================================================

max_steps = num_epochs * len(train_examples) // batch_size

def get_lr(step):
    if step < warmup_steps:
        return learning_rate * step / max(warmup_steps, 1)
    progress = (step - warmup_steps) / max(max_steps - warmup_steps, 1)
    coeff    = 0.5 * (1.0 + math.cos(math.pi * progress))
    return min_lr + coeff * (learning_rate - min_lr)


# ========================================================================
# TRAINING
# ========================================================================

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=learning_rate,
    betas=(0.9, 0.95),
    weight_decay=0.1,
)

start_step, best_val_loss = load_resume_checkpoint(optimizer)

print(f"\nFine-tuning for {num_epochs} epochs ({max_steps:,} steps)...")
print(f"  Arch:      {n_layer} blocks × {n_head} heads × {n_embd} dims")
print(f"  Vocab:     {TOTAL_VOCAB:,} (50,257 + 4 special tokens)")
print(f"  Batch:     {batch_size}")
print(f"  LR:        {learning_rate} → {min_lr} (cosine, {warmup_steps} warmup)")
print(f"  Grad clip: {grad_clip}")
print(f"  Save every: {save_every} steps\n")

t0 = time.time()

for step in range(start_step, max_steps + 1):

    # ------------------------------------------------------------------
    # Evaluation + checkpoint
    # ------------------------------------------------------------------
    if step % eval_interval == 0:
        losses  = estimate_loss()
        elapsed = time.time() - t0
        lr_now  = get_lr(step)
        epoch   = step * batch_size / len(train_examples)

        print(f"  step {step:>5,} | epoch {epoch:.2f} | "
              f"train {losses['train']:.4f} | val {losses['val']:.4f} | "
              f"lr {lr_now:.1e} | {elapsed:.0f}s")

        # Save best checkpoint
        if losses['val'] < best_val_loss:
            best_val_loss = losses['val']
            save_checkpoint(BEST_CKPT, step, best_val_loss.item(), optimizer)
            print(f"   ✓ Best checkpoint saved (val {best_val_loss:.4f})")

    # Periodic save every N steps (safety net)
    if step > 0 and step % save_every == 0:
        save_checkpoint(PERIODIC_CKPT, step, best_val_loss, optimizer)
        print(f"   💾 Periodic checkpoint saved (step {step:,})")

    if step == max_steps:
        break

    # ------------------------------------------------------------------
    # LR update
    # ------------------------------------------------------------------
    lr = get_lr(step)
    for pg in optimizer.param_groups:
        pg['lr'] = lr

    # ------------------------------------------------------------------
    # Forward + backward
    # ------------------------------------------------------------------
    x, y = get_batch(train_examples)
    _, loss = model(x, y)

    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
    optimizer.step()


# ========================================================================
# CHAT INFERENCE
# ========================================================================

try:
    import tiktoken
    enc = tiktoken.get_encoding('gpt2')

    def chat(user_message, system="You are Teja, a helpful AI assistant built from scratch."):
        """Run a single conversation turn."""
        model.eval()
        sys_ids  = [SYSTEM_TOKEN] + enc.encode(system)       + [EOT_TOKEN]
        user_ids = [USER_TOKEN]   + enc.encode(user_message) + [EOT_TOKEN]
        asst_ids = [ASSISTANT_TOKEN]

        prompt = sys_ids + user_ids + asst_ids
        idx    = torch.tensor([prompt], dtype=torch.long, device=device)

        out    = model.generate(idx, max_new_tokens=200)
        # Decode only the new tokens (after the prompt)
        new_tokens = out[0, len(prompt):].tolist()
        # Remove EOT and any special tokens (ids >= 50257)
        if EOT_TOKEN in new_tokens:
            new_tokens = new_tokens[:new_tokens.index(EOT_TOKEN)]
        new_tokens = [t for t in new_tokens if t < 50_257]
        return enc.decode(new_tokens)

    print("\n" + "="*60)
    print("  TEJA CHAT — Stage 7 Fine-Tuned")
    print("="*60)

    test_prompts = [
        "What is the capital of France?",
        "Write a short poem about learning.",
        "Explain what a neural network is in simple terms.",
    ]

    for prompt in test_prompts:
        print(f"\nUser:  {prompt}")
        print(f"Teja:  {chat(prompt)}")

except ImportError:
    print("(Install tiktoken to see chat demo)")


# ========================================================================
# FINAL SUMMARY
# ========================================================================
losses = estimate_loss()
save_checkpoint(BEST_CKPT, max_steps, losses['val'].item(), optimizer)

print(f"""
{'='*60}
  TEJA — Stage 7 Complete!
{'='*60}

  Parameters:      {total_params:,}
  Best val loss:   {best_val_loss:.4f}
  Final val loss:  {losses['val']:.4f}
  Epochs:          {num_epochs}
  Dataset:         Stanford Alpaca (52K instructions)

  WHAT CHANGED FROM STAGE 5 → STAGE 7:
    Pretrained on: OpenWebText (raw text completion)
    Fine-tuned on: Alpaca (instruction-response pairs)
    Special tokens: <|system|> <|user|> <|assistant|> <|endofturn|>
    Loss masking:   Only assistant responses contribute to loss
    LR:             3e-4 (pretrain) → 1e-4 (fine-tune)

  WHAT COMES NEXT:
    Stage 8: Scale to hundreds of millions of parameters
    Stage 9: RLHF — Reinforcement Learning from Human Feedback
{'='*60}
""")
